### ISSUE TITLE
Use markup instead of JSON as the data source

### ISSUE THREAD

**Issue by warpech** [Juicy/x-breadcrumb#1]
For the list of options, use markup instead of JSON.

Change:

``` html
<x-crumb value="Food" dropdown="true" alloptions=["Food","Clothing","Housing"] dataListId="firstLevelOptions"></x-crumb>
```

To something like this:

``` html
<x-crumb value="Food" dropdown="true">
  <ul>
    <li onclick="console.log('Food selected')">Food</li>
    <li onclick="console.log('Clothing selected')">Clothing</li>
    <li onclick="console.log('Housing selected')">Housing</li>
  </ul>
</x-crumb>
```

Important: x-crumb does not need to have any logic for searching the options. That logic will be on server (triggered from client in the onclick handler).

**Comment by saurshaz** [comment]
- changed from array to inner markup
- TODO :: `x-crumb does not need to have any logic for searching the options``

**Comment by saurshaz** [comment]
`x-crumb does not need to have any logic for searching the options`
addressed
