### ISSUE TITLE
Dropdown should be absolutely positioned

### ISSUE THREAD

**Issue by warpech** [Juicy/x-breadcrumb#10]
Dropdown should appear absolutely positioned below the x-crumb. Currently it is relatively positioned, which causes the container to expand:

![bug](https://cloud.githubusercontent.com/assets/566463/11901028/a31a53cc-a5a9-11e5-8a78-1d1c31aadb7b.gif)

This should be done using absolute positioning of the Shady DOM of x-crumb (so the style is in `x-crumb.html`, not in `pim-demo-element.html` where it is used).

**Comment by saurshaz** [comment]
Fixed. please check
