### ISSUE TITLE
Clicking outside of the dropdown should close the dropdown

### ISSUE THREAD

**Issue by warpech** [Juicy/x-breadcrumb#11]
Clicking outside of the dropdown should close the dropdown

![bug](https://cloud.githubusercontent.com/assets/566463/11901247/c8baf022-a5aa-11e5-8838-ff6ea842f653.gif)

**Comment by saurshaz** [comment]
made checkboxes off on selection of anyother checkbox

**Comment by saurshaz** [comment]
Missing a scenario

**Comment by saurshaz** [comment]
made checkboxes off on click of anything outside the selection label
