### ISSUE TITLE
Ghost should be gray with opacity 50%

### ISSUE THREAD

**Issue by warpech** [Juicy/x-breadcrumb#12]
Ghost x-crumbs should have gray background with opacity 50% (not light blue like the active element)

<img width="787" alt="screen shot 2015-12-18 at 17 17 01" src="https://cloud.githubusercontent.com/assets/566463/11901309/47339760-a5ab-11e5-83e9-d87a01c397b0.png">

**Comment by saurshaz** [comment]
made the color change, with opacity 0.5
