### ISSUE TITLE
Vertical mode is missing

### ISSUE THREAD

**Issue by warpech** [Juicy/x-breadcrumb#13]
According to the spec, there should be a horizontal and vertical mode.

Currently only horizontal mode is available.

This is of low priority right now.

<img width="850" alt="screen shot 2015-12-18 at 17 21 18" src="https://cloud.githubusercontent.com/assets/566463/11901412/c554dece-a5ab-11e5-9bb4-2c6e7d77d5b6.png">

**Comment by saurshaz** [comment]
fixed orientation options vertical/horizontal.

shown in pim-x-element-vertical.html & pim-x-element.html
