### ISSUE TITLE
No styles with the real Shadow DOM enabled

### ISSUE THREAD

**Issue by warpech** [Juicy/x-breadcrumb#21]
When I enable Shadow DOM in Polymer by replacing:

``` html
  <script src="../webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="../polymer/polymer.html">
```

With:

``` html
  <script src="../webcomponentsjs/webcomponents.js"></script>
  <script>
    window.Polymer = window.Polymer || {};
    window.Polymer.dom = "shadow";
  </script>
  <link rel="import" href="../polymer/polymer.html">
```

The elements in demo **usage.html** appear unstyled:

<img width="1421" alt="screen shot 2016-01-07 at 11 50 24" src="https://cloud.githubusercontent.com/assets/566463/12168799/f28cf410-b534-11e5-8874-6f42c5a43837.png">

With Shady DOM it looks like this:

<img width="1435" alt="screen shot 2016-01-07 at 11 49 47" src="https://cloud.githubusercontent.com/assets/566463/12168798/ef1c3e8a-b534-11e5-8c24-7e15946b3898.png">

**Comment by warpech** [comment]
@miyconst could you pls help?

**Comment by miyconst** [comment]
The `::content` styles in Shady DOM also affect the elements of an element, not only the distributed nodes. When switched to native Shadow DOM such styles are applied only to the distributed nodes inside `<content>`.

Example to explain more:

### A custom element

``` html
<dom-module is="x-content">
    <template>
        <style>
            ::content div { background-color: red; }
        </style>
        <div>I am red in Shady DOM, but I am NOT red in Shadow DOM!</div>
        <content></content>
    </template>
    <script>
        Polymer({ is: "x-content" });
    </script>
</dom-module>
```

### Usage

``` html
<x-content>
    <div>I am always red!</div>
</x-content>
```

**Comment by warpech** [comment]
Fixed

**Comment by warpech** [comment]
Thanks @miyconst!
