### ISSUE TITLE
x-crumbs should look more like in the spec

### ISSUE THREAD

**Issue by warpech** [Juicy/x-breadcrumb#3]
x-crumbs should be arrow shaped as in the spec.

This can be done SVG or some CSS3 technique

<img width="503" alt="screen shot 2015-12-09 at 15 07 08" src="https://cloud.githubusercontent.com/assets/566463/11687370/8bd0641a-9e86-11e5-9ad6-0d9ef8406c98.png">

**Comment by saurshaz** [comment]
Work is done on this. still icons are being worked upon. so keeping this open.

**Comment by saurshaz** [comment]
Looks like the spec now. 
As per the updated pdf -

https://gyazo.com/864958cadab47220b06ac7996d550f0d

So, closing this one.
