### ISSUE TITLE
x-crumb should have an "active" attribute

### ISSUE THREAD

**Issue by warpech** [Juicy/x-breadcrumb#4]
We will need to highlight a certain "x-crumb" using an `active` attribute (`<x-crumb active>`). Should look like on the below image.

The "+" button might also have the `active` attribute.

<img width="484" alt="screen shot 2015-12-09 at 15 08 41" src="https://cloud.githubusercontent.com/assets/566463/11687421/e076a6be-9e86-11e5-8607-c7fcda4bba6c.png">

**Comment by saurshaz** [comment]
Added active attribute.

the exact styling of add button and the drop down icon is something that remains 

For the UI changes - referencing issue #3  .closing this one
