### ISSUE TITLE
x-crumb should have a "ghost" attribute

### ISSUE THREAD

**Issue by warpech** [Juicy/x-breadcrumb#5]
We will use it on breadcrumbs that are on the right hand side of an "active" x-crumb.

This only changes the appearance.

A "ghost" element has the same background color as the normal attribute but with 25% opacity.

<img width="335" alt="screen shot 2015-12-11 at 10 55 42" src="https://cloud.githubusercontent.com/assets/566463/11740880/c6189d52-9ff5-11e5-983d-c0a216b300ed.png">

**Comment by saurshaz** [comment]
updating ui - adding ghost feature attribute driven

The UI will be refined further, and that can be covered in the other issue #3
