### ISSUE TITLE
Make the gh-pages demo work

### ISSUE THREAD

**Issue by tomalec** [Juicy/x-breadcrumb#9]
It would be nice if the demo, will work on GitHub pages
http://juicy.github.io/x-breadcrumb/demo.html

I think, we can also abandon master branch in favor of gh-pages only (as we do in other juicy- repos)

**Comment by saurshaz** [comment]
Have made a demo working at - `http://juicy.github.io/x-breadcrumb/index.html`

dependent on polymer's 1.2.3
